INSERT INTO SYS_ACCOUNT(ACCOUNT_ID, USER_NAME, ACCOUNT, PASSWORD, ROLE_ID, CREATE_TIME) VALUES ( 1, 'JiaHong', 'jiahong0412', '$2a$10$vCWTSe.NBd81SyF6OAaKBO2eOWk7INXg6hDHjVm5WOV7/Ie0ZNlUm', '1', '2020-11-08 16:20:18.991');
INSERT INTO SYS_ACCOUNT(ACCOUNT_ID, USER_NAME, ACCOUNT, PASSWORD, ROLE_ID, CREATE_TIME) VALUES ( 2, 'User', 'user001', '$2a$10$4EysN7oRMkL7MFMAze2UcejFMWCPdrfNkHrOEukFolcG/RFs7q.oW', '0', '2020-11-08 16:20:18.991');

INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, REMARK, LEVEL) VALUES ( 1, 'SuperAdmin', '系統管理員', 2 );
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, REMARK, LEVEL) VALUES ( 2, 'Admin', '一般管理者', 1 );
INSERT INTO SYS_ROLE(ROLE_ID, ROLE_NAME, REMARK, LEVEL) VALUES ( 3, 'User', '一般使用者', 0 );